"""credit card bills, account opening balance, lending transaction link

Revision ID: 27186433c65c
Revises: c5ab5d6fc83a
Create Date: 2026-09-11 14:29:20.974015

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27186433c65c'
down_revision: str | Sequence[str] | None = 'c5ab5d6fc83a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card_bills',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credit_card_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_bills_credit_card_id'), 'credit_card_bills', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_credit_card_bills_user_id'), 'credit_card_bills', ['user_id'], unique=False)
    op.add_column(
        'financial_accounts',
        sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'),
    )
    op.alter_column('financial_accounts', 'opening_balance', server_default=None)
    op.add_column('lendings', sa.Column('transaction_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'lendings', 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lendings', type_='foreignkey')
    op.drop_column('lendings', 'transaction_id')
    op.drop_column('financial_accounts', 'opening_balance')
    op.drop_index(op.f('ix_credit_card_bills_user_id'), table_name='credit_card_bills')
    op.drop_index(op.f('ix_credit_card_bills_credit_card_id'), table_name='credit_card_bills')
    op.drop_table('credit_card_bills')
    # ### end Alembic commands ###
