"""lending payments for partial repayments

Revision ID: 6c6096abe0c8
Revises: 3a917ec19c40
Create Date: 2026-09-24 10:26:03.740992

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c6096abe0c8'
down_revision: str | Sequence[str] | None = '3a917ec19c40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lending_payments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lending_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lending_id'], ['lendings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lending_payments_lending_id'), 'lending_payments', ['lending_id'], unique=False)
    op.create_index(op.f('ix_lending_payments_user_id'), 'lending_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lending_payments_user_id'), table_name='lending_payments')
    op.drop_index(op.f('ix_lending_payments_lending_id'), table_name='lending_payments')
    op.drop_table('lending_payments')
    # ### end Alembic commands ###
