"""routine completion time of day

Revision ID: 6ee42a9c9024
Revises: 6c6096abe0c8
Create Date: 2026-09-28 13:48:39.578119

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ee42a9c9024'
down_revision: str | Sequence[str] | None = '6c6096abe0c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine_completions', sa.Column('completed_at', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routine_completions', 'completed_at')
    # ### end Alembic commands ###
