"""credit cards, emis, sips, lending

Revision ID: c5ab5d6fc83a
Revises: 895c1a5cfc76
Create Date: 2026-09-11 13:46:28.092399

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5ab5d6fc83a'
down_revision: str | Sequence[str] | None = '895c1a5cfc76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lendings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('person_name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('given_on', sa.Date(), nullable=False),
    sa.Column('remind_on', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('settled_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lendings_user_id'), 'lendings', ['user_id'], unique=False)
    op.create_table('credit_cards',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_cards_account_id'), 'credit_cards', ['account_id'], unique=True)
    op.create_index(op.f('ix_credit_cards_user_id'), 'credit_cards', ['user_id'], unique=False)
    op.create_table('sips',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sips_account_id'), 'sips', ['account_id'], unique=False)
    op.create_index(op.f('ix_sips_next_due_date'), 'sips', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_sips_user_id'), 'sips', ['user_id'], unique=False)
    op.create_table('emis',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credit_card_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_installments', sa.Integer(), nullable=False),
    sa.Column('installments_paid', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emis_credit_card_id'), 'emis', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_emis_next_due_date'), 'emis', ['next_due_date'], unique=False)
    op.create_index(op.f('ix_emis_user_id'), 'emis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emis_user_id'), table_name='emis')
    op.drop_index(op.f('ix_emis_next_due_date'), table_name='emis')
    op.drop_index(op.f('ix_emis_credit_card_id'), table_name='emis')
    op.drop_table('emis')
    op.drop_index(op.f('ix_sips_user_id'), table_name='sips')
    op.drop_index(op.f('ix_sips_next_due_date'), table_name='sips')
    op.drop_index(op.f('ix_sips_account_id'), table_name='sips')
    op.drop_table('sips')
    op.drop_index(op.f('ix_credit_cards_user_id'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_account_id'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('ix_lendings_user_id'), table_name='lendings')
    op.drop_table('lendings')
    # ### end Alembic commands ###
